# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcdf16c5a1e552e1be7af29cc4d816f53b5fa5eb5da95dc8d09d1b3acafc80a16c87c84131fae180502845b960ebda4f103656ccaa3dede017171e373d6fd040

test:
  secret_key_base: a84db4b20ba0a08b6f6f52ed3c398b481264d2703d1792851b85d606019442c0b0b19da4ed2a0a0dd80dace829f041c9dfdf16a85e5b2a52d568fed37dec835a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
